import toyotaCoaster from "./images/coaster.jpg";
import toyotaCoaster1 from "./images/coaster1.jpg";

export const imageSources = {
  // Homepage banner 2 and hero-side card.
  makkah: "/images/makkah.jpg",
  // Homepage banner 1 and the Why Manar section.
  whyManar: "/images/why-manar.jpg",
  // Homepage: More Than a Transfer section.
  moreThanTransfer: "/images/more-than-transfer.jpg",
  madinah: "/images/madinah.jpg",
  hajj: "/images/hajj.jpg",
  umrah: "/images/umrah.jpg",
  pilgrimage: "/images/pilgrimage.jpg",
  airportService: "/images/airport-service.jpg",
  makkahService: "/images/makkah-service.jpg",
  madinahService: "/images/madinah-service.jpg",
  ziyaratService: "/images/ziyarat-service.jpg",
  intercityService: "/images/intercity-service.jpg",
  vipService: "/images/vip-service.jpg",
  airportPickDropService: "/images/Airport%20Pick%20&%20Drop.jpg",
  makkahTransfersService: "/images/Makkah%20Transfers.jpg",
  madinahTransfersService: "/images/Madinah%20Transfers.jpg",
  ziyaratTransportationService: "/images/Ziyarat%20Transportation.jpg",
  intercityTransfersService: "/images/Intercity%20Transfers.jpg",
  vipTransportationService: "/images/VIP%20Transportation.jpg",
  sedan: "/images/sedan.jpg",
  van: "/images/airport-service.jpg",
  stariaExterior: "/images/Hyundai%20Staria%202025-26-1.png",
  stariaExteriorSide: "/images/Hyundai%20Staria%202025-26-2.jpg",
  stariaExteriorFront: "/images/Hyundai%20Staria%202025-26-3.jpg",
  gmcYukon: "/images/GMC%20Yukon%20XL-1.jpg",
  bus1: "/images/Bus-1.jpg",
  bus2: "/images/Bus-2.jpg",
  toyotaCoaster,
  toyotaCoaster1,
  hyundaiStarex1: "/images/Hyundai%20statex-1.jpg",
  hyundaiStarex2: "/images/Hyundai%20statex-2.jpg",
  hyundaiStarex3: "/images/Hyundai%20statex-3.jpg",
  hyundaiStarex4: "/images/Hyundai%20statex-4.jpg",
  hyundaiStarex5: "/images/Hyundai%20statex-5.jpg",
  hyundaiStarex6: "/images/Hyundai%20statex-6.jpg",
  hyundaiStarex7: "/images/Hyundai%20statex-7.jpg",
  toyotaHiace1: "/images/Toyota%20Hiace-1.jpg",
  toyotaHiace2: "/images/Toyota%20Hiace-2.jpg",
  toyotaHiace3: "/images/Toyota%20Hiace-3.jpg",
  toyotaCamry1: "/images/Toyota%20Camry%202025-26.png",
  toyotaCamry2: "/images/Toyota%20camry-2.jpg",
  toyotaCamry3: "/images/Toyota%20camry-3.jpg",
  toyotaCamry4: "/images/Toyota%20camry-4.jpg",
  toyotaCamry5: "/images/Toyota%20camry-5.jpg",
  // Homepage: The Fleet section uses each vehicle image from this catalog.
  suv: "/images/suv.jpg",
  company: "/images/company.jpg",
  story: "/images/story.jpg",
  ceo: "/images/ceo.jpg",
  useful: "/images/useful.jpg",
  travel: "/images/travel.jpg",
  policy: "/images/policy.jpg",
  partner: "/images/partner.jpg",
  login: "/images/login.jpg",
  commission: "/images/commission.jpg",
} as const;